quarkus:
  http:
    port: 8080
    cors:
      origins: /.*/

prod:
  hibernate-orm:
    database:
      database:
        generation: update

  datasource:
    username: postgres
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/students-demo

  application:
    name: students-hibernate

